/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "menu_calculadora.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
calcprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		intpair suma_1_arg;
		intpair resta_1_arg;
		intpair multiplica_1_arg;
		doublepair divide_1_arg;
		vectorpair suma_vector_1_arg;
		vectorpair resta_vector_1_arg;
		vectorpair producto_vector_1_arg;
		matrizpair suma_matriz_1_arg;
		matrizpair resta_matriz_1_arg;
		matrizpair producto_matriz_1_arg;
		doublepair logaritmo_1_arg;
		double seno_1_arg;
		double cos_1_arg;
		doublepair area_triangulo_1_arg;
		doublepair area_rectangulo_1_arg;
		doublepair area_circulo_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SUMA:
		_xdr_argument = (xdrproc_t) xdr_intpair;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) suma_1_svc;
		break;

	case RESTA:
		_xdr_argument = (xdrproc_t) xdr_intpair;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) resta_1_svc;
		break;

	case MULTIPLICA:
		_xdr_argument = (xdrproc_t) xdr_intpair;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) multiplica_1_svc;
		break;

	case DIVIDE:
		_xdr_argument = (xdrproc_t) xdr_doublepair;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) divide_1_svc;
		break;

	case SUMA_VECTOR:
		_xdr_argument = (xdrproc_t) xdr_vectorpair;
		_xdr_result = (xdrproc_t) xdr_resultvector;
		local = (char *(*)(char *, struct svc_req *)) suma_vector_1_svc;
		break;

	case RESTA_VECTOR:
		_xdr_argument = (xdrproc_t) xdr_vectorpair;
		_xdr_result = (xdrproc_t) xdr_resultvector;
		local = (char *(*)(char *, struct svc_req *)) resta_vector_1_svc;
		break;

	case PRODUCTO_VECTOR:
		_xdr_argument = (xdrproc_t) xdr_vectorpair;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) producto_vector_1_svc;
		break;

	case SUMA_MATRIZ:
		_xdr_argument = (xdrproc_t) xdr_matrizpair;
		_xdr_result = (xdrproc_t) xdr_resultmatriz;
		local = (char *(*)(char *, struct svc_req *)) suma_matriz_1_svc;
		break;

	case RESTA_MATRIZ:
		_xdr_argument = (xdrproc_t) xdr_matrizpair;
		_xdr_result = (xdrproc_t) xdr_resultmatriz;
		local = (char *(*)(char *, struct svc_req *)) resta_matriz_1_svc;
		break;

	case PRODUCTO_MATRIZ:
		_xdr_argument = (xdrproc_t) xdr_matrizpair;
		_xdr_result = (xdrproc_t) xdr_resultmatriz;
		local = (char *(*)(char *, struct svc_req *)) producto_matriz_1_svc;
		break;

	case LOGARITMO:
		_xdr_argument = (xdrproc_t) xdr_doublepair;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) logaritmo_1_svc;
		break;

	case SENO:
		_xdr_argument = (xdrproc_t) xdr_double;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) seno_1_svc;
		break;

	case COS:
		_xdr_argument = (xdrproc_t) xdr_double;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) cos_1_svc;
		break;

	case AREA_TRIANGULO:
		_xdr_argument = (xdrproc_t) xdr_doublepair;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) area_triangulo_1_svc;
		break;

	case AREA_RECTANGULO:
		_xdr_argument = (xdrproc_t) xdr_doublepair;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) area_rectangulo_1_svc;
		break;

	case AREA_CIRCULO:
		_xdr_argument = (xdrproc_t) xdr_doublepair;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) area_circulo_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CALCPROG, CALCULADORA);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCPROG, CALCULADORA, calcprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCPROG, CALCULADORA, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCPROG, CALCULADORA, calcprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCPROG, CALCULADORA, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
