/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "menu_calculadora.h"

bool_t
xdr_intpair (XDR *xdrs, intpair *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_doublepair (XDR *xdrs, doublepair *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resultvector (XDR *xdrs, resultvector *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->resultvector_val, (u_int *) &objp->resultvector_len, 30,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resultmatriz (XDR *xdrs, resultmatriz *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->resultmatriz_val, (u_int *) &objp->resultmatriz_len, 60,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_matrizpair (XDR *xdrs, matrizpair *objp)
{
	register int32_t *buf;

	 if (!xdr_resultmatriz (xdrs, &objp->m1))
		 return FALSE;
	 if (!xdr_resultmatriz (xdrs, &objp->m2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_vectorpair (XDR *xdrs, vectorpair *objp)
{
	register int32_t *buf;

	 if (!xdr_resultvector (xdrs, &objp->v1))
		 return FALSE;
	 if (!xdr_resultvector (xdrs, &objp->v2))
		 return FALSE;
	return TRUE;
}
