/* dir_server.c : código del servidor   */
/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include "dir.h" /* creado por rpcgen */
#include <dirent.h>
#include <errno.h>

readdir_res *
readdir_1_svc(nametype dirname, struct svc_req *rqstp)
{
	DIR *dirp;
	struct dirent *d;
	namelist nl;
	namelist *nlp;

	static readdir_res result;

	dirp = opendir(dirname);
	if (dirp == (DIR *)NULL)
	{
		result.errnum = errno;
		return (&result);
	}
	/*
	 * La siguiente línea de código libera la memoria que se asignó
	 * (para el resultado) en una ejecución previa del servidor
	 */
	xdr_free(xdr_readdir_res, &result);

	nlp = &result.readdir_res_u.list;
	while (d = readdir(dirp))
	{
		nl = *nlp = (namenode *)malloc(sizeof(namenode));
		if (nl == (namenode *)NULL)
		{
			result.errnum = 10;
			closedir(dirp);
			return (&result);
		}
		nl->name = strdup(d->d_name);
		nlp = &nl->next;
	}
	*nlp = (namelist)NULL;
	result.errnum = 0;
	closedir(dirp);
	return (&result);
}
