/* dir_client.c: código del cliente       */
/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include "dir.h" /* creado por rpcgen */
#include <errno.h>

void dirprog_1(char *server, nametype dir)
{
	CLIENT *clnt;
	readdir_res *result;
	namelist nl;

#ifndef DEBUG
	clnt = clnt_create(server, DIRPROG, DIRVER, "udp");
	if (clnt == (CLIENT *)NULL)
	{
		clnt_pcreateerror(server);
		exit(1);
	}
#endif /* DEBUG */

	result = readdir_1(dir, clnt);
	if (result == (readdir_res *)NULL)
	{
		clnt_perror(clnt, server);
		exit(1);
	}

	if (result->errnum != 0)
	{
		errno = result->errnum;
		perror(dir);
		exit(1);
	}

	for (nl = result->readdir_res_u.list; nl != NULL; nl = nl->next)
		printf("%s\n", nl->name);

	xdr_free(xdr_readdir_res, result);

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */

	exit(0);
}
main(int argc, char *argv[])
{
	char *server;
	nametype dir;
	setbuf(stdout, NULL);
	if (argc < 3)
	{
		printf("usage:  %s server_host directory\n", argv[0]);
		exit(1);
	}
	server = argv[1];
	dir = argv[2];
	dirprog_1(server, dir);
}
